# Generated by Django 3.1.2 on 2020-12-03 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=64)),
                ('paciente_apellido', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_category', models.TextField(blank=True, null=True)),
                ('prod_title', models.CharField(max_length=220)),
                ('prod_desc', models.TextField(blank=True, null=True)),
                ('prod_lente_cercania', models.TextField(blank=True, choices=[('LJ', 'Lejos'), ('CR', 'Cerca')], null=True)),
                ('prod_lente_lado', models.TextField(blank=True, choices=[('IZ', 'Izquierda'), ('DE', 'Derecha')], null=True)),
                ('prod_lente_armazon', models.BooleanField(blank=True, null=True)),
                ('prod_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diahora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('asistencia', models.CharField(choices=[('0', 'No'), ('1', 'Sí'), ('2', 'Pendiente')], default='2', max_length=9)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_paciente', to='products.paciente')),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_medicos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('Pend', 'Pendiente'), ('Ped', 'Pedido'), ('Ta', 'Taller'), ('Fin', 'Finalizado')], default='Pend', max_length=10)),
                ('tipo_pago', models.CharField(choices=[('TCred', 'Tarjeta de Crédito'), ('TDeb', 'Tarjeta de Débito'), ('BV', 'Billetera Virtual'), ('EFT', 'Efectivo')], default='EFT', max_length=25)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to='products.paciente')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_pedido', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cantidad_pedido', models.IntegerField()),
                ('subtotal_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='products.pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicion', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diahora', models.DateTimeField(auto_now=True)),
                ('observacion', models.TextField()),
                ('paciente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='historia', to='products.paciente')),
                ('profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
